version: '3.8'

services:
  asterisk:
    # openstec/itc-conector イメージを使用
    image: openstec/itc-conector
    # コンテナに分かりやすい名前を付ける
    container_name: asterisk-server
    # コンテナを常に再起動するポリシー
    restart: always
    ports:
      - "3000:3000"
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "10000-20000:10000-20000/udp"
    # ボリュームのマウント設定
    # 左側(ホスト)の ./conf ディレクトリを、右側(コンテナ)の /etc/asterisk にマウント
    volumes:
      - ./conf:/etc/asterisk
      - ./moh:/var/lib/asterisk/moh
      - ./sounds:/usr/local/share/asterisk/sounds/
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
